### ISSUE TITLE
Remove address from KrakenWebSocket interface and its implementations

### ISSUE THREAD

**Issue by louisinger** [TDex-network/tdex-feeder#20]
https://github.com/TDex-network/tdex-feeder/blob/3ae029cc28c85bc0ad547847c561b79d209cb31a/internal/ports/kraken_websocket.go#L31-L32

`address` is not used in `Connect` ---> kraken WS endpoint is not configurable via `go_kraken`. we should remove (also from config file)

**Comment by tiero** [comment]
Would be interesting to have a way to switch the price feeder then, we may create an enum-like for each one. maybe in a new issue
